slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /navigation/filtered_scan
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.25
    transform_publish_period: 0.05
    map_update_interval: 2.0
    throttle_scans: 1
    enable_interactive_mode: false
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 6
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
